### ISSUE TITLE
Why both Wireproxy and python-proxy exist simultaneously

### ISSUE THREAD

**Issue by hua-ying** [105PM/docker-warproxy#3]
First of all, thanks for your open-source this amazing project!

I'm wondering why these two proxy (wire-proxy and python-proxy) exist at the same time, 
is that these two probably do the same thing?

**Comment by by275** [comment]
pproxy is to secure with a password in case it is published publicly.

**Comment by hua-ying** [comment]
> pproxy is to secure with a password in case it is published publicly.

If so, can we take them apart? The benefits are:
- socks5 auth is actually optional, it makes more architectural sense as an additional service;
- Dockerfile layer is clearer and reduces unnecessary layers;

**Comment by by275** [comment]
pproxy can be selectively turned off by `PROXY_ENABLED=false`. Removing pproxy from the image entirely is up to the repository owner's choice.

**Comment by hua-ying** [comment]
I got.

**Comment by by275** [comment]
At the time of writing, we haven't noticed sock5 authentication was there. The owner will test removing `pproxy` things from the current implementation.
